### PR TITLE
Fix docker builds

### PR DESCRIPTION
**Pull request by ppettit**
Fixes docker builds, adds auto building using gitlab ci if available and also tidies up the cookie stuff.

This updates Meteor to version 1.4.3.2

Many thanks to @androidwiltron for help with this!

### CODE REVIEW

**Comment by pmgration** [comment]
Nice work @ppettit and @androidwilton! Not sure when I'll get round to testing this yet though... while you've got the codebase and docker changes fresh in your mind, can you think of a way to resolve #28?

**Comment by androidwiltron** [comment]
I guess we could copy the part of the git config it needs into the correct
dir on docker-compose?

**Comment by ppettit** [comment]
maybe, or perhaps write the version stuff into a file or env variables or something? currently `.dockerignore` excludes all of `.git` for size/speed reasons. i will investigate...

**Comment by androidwiltron** [comment]
Hey i've been testing this PR for the past couple of days and its working well for me. should really get this in as peakaboo dockerized doesnt work without it

**Comment by ppettit** [comment]
hey @pmgration are you happy for me to merge this (and #37) - i think i have permissions!

or are you likely to be able to do it?

should probably actually also upgrade meteor again which should allow building on docker hub i think, but this is a good start and @androidwiltron says it works for him too so you can blame him if it is bad 😉

**Comment by androidwiltron** [comment]
Hahaha! So I've upgraded to the latest meteor in testing on my branch and
it works ok. Still testing. I ran into a bit of a hitch at first. It's
worth deleting ~/.meteor first so it fresh and I also had some bad npm
stuff cached so I needed to delete the project folder and clone again
(suppose i could have deleted the npm cache)

**Comment by pmgration** [comment]
@ppettit feel free to merge if you like, I've also invited @androidwiltron to have write permissions on the repository so he should be able to merge things in future if he accepts.

**Comment by pmgration** [comment]
@androidwiltron if you're happy with the testing then you're welcome to merge this one now that you have the permissions - always preferable to have someone other than the creator of the PR do the accepting and merging of it and I probably won't get chance to have a look at this one in detail for a while yet

**Comment by androidwiltron** [comment]
thanks much @ppettit for the PR to get things working again and @pmgration for the unlimited power :laughing:

**Pull request merged**
